### ISSUE TITLE
Tarea #8: Integración de redes sociales

### ISSUE THREAD

**Issue by Angie222** [Angie222/Proyecto-AppTurismoCity#11]
Agrega botones de compartir en redes sociales y enlaces a perfiles sociales relevantes para permitir a los usuarios compartir y promover los destinos y actividades en sus propias cuentas.

**Comment by zoeggr** [comment]
[https://instagram.com/estuu_arguello?igshid=YmM0MjE2YWMzOA==](url)
[https://instagram.com/ann_ontivero?igshid=YmM0MjE2YWMzOA==](url)
[https://instagram.com/caos.lm?igshid=YmM0MjE2YWMzOA==](url)
[https://instagram.com/militahuerta?igshid=YmM0MjE2YWMzOA==](url)
[https://instagram.com/abel_8.3?igshid=YmM0MjE2YWMzOA==](url)
[https://instagram.com/zoeg.gr?igshid=MzNlNGNkZWQ4Mg==](url)
