### ISSUE TITLE
Tarea #9: Implementación de sistema de comentarios y reseñas

### ISSUE THREAD

**Issue by Angie222** [Angie222/Proyecto-AppTurismoCity#12]
Desarrolla un sistema que permita a los usuarios dejar comentarios y reseñas sobre los destinos y las experiencias turísticas.

**Comment by merceaudisio** [comment]
![WhatsApp Image 2023-06-29 at 10 41 41 (1)](https://github.com/Angie222/Proyecto-AppTurismoCity/assets/135723917/51b7ff38-32a3-4015-849b-c30e9012e818)
![WhatsApp Image 2023-06-29 at 10 41 41](https://github.com/Angie222/Proyecto-AppTurismoCity/assets/135723917/f8e82424-da0b-4da6-b779-b5890e004828)
