### ISSUE TITLE
Tarea #2: Crear sistemap

### ISSUE THREAD

**Issue by Angie222** [Angie222/Proyecto-AppTurismoCity#2]
Creamos un mapa de navegación para guiar a los usuarios con herramientas online.
Se proponen opciones

**Comment by merceaudisio** [comment]
![capture-20230627-151644](https://github.com/Angie222/Proyecto-AppTurismoCity/assets/135723917/28c9cce6-b71a-4925-8d86-f779151406ba)

**Comment by merceaudisio** [comment]
Sistema map
