### ISSUE TITLE
Tarea #4: Index.HTML

### ISSUE THREAD

**Issue by Angie222** [Angie222/Proyecto-AppTurismoCity#6]
Editar el index.html para armar la estructura semántica a fin de determinar el encabezado, sección principal y pie de página, divs, títulos por secciones y elementos principales

**Comment by zoeggr** [comment]
[Pagina Curso.zip](https://github.com/Angie222/Proyecto-AppTurismoCity/files/11893558/Pagina.Curso.zip)

**Comment by zoeggr** [comment]
Página en su estado inicial.
