### ISSUE TITLE
Tarea #5: Formulario

### ISSUE THREAD

**Issue by Angie222** [Angie222/Proyecto-AppTurismoCity#7]
En el archivo de contacto de HTML, crear el formulario.

**Comment by Mili200410** [comment]
![capture-20230628-100326](https://github.com/Angie222/Proyecto-AppTurismoCity/assets/135728367/d2fe01ba-0202-4272-ba22-410c4f32a8f4)
![capture-20230628-100444](https://github.com/Angie222/Proyecto-AppTurismoCity/assets/135728367/553618aa-cd15-478c-9f54-57fcfd800a2f)

**Comment by Mili200410** [comment]
Página zip
[Pagina Curso.zip](https://github.com/Angie222/Proyecto-AppTurismoCity/files/11895036/Pagina.Curso.zip)
