### ISSUE TITLE
Tarea #6: Historias de usuario

### ISSUE THREAD

**Issue by Angie222** [Angie222/Proyecto-AppTurismoCity#9]
Esta es la segunda tarea PARA CADA UNO, consiste en crear las historias de usuario relacionadas con la clase (Metodologías Ágiles). 
La tercer tarea para todos se presentará más tarde.

**Comment by Angie222** [comment]
[Scrum.xlsx](https://github.com/Angie222/Proyecto-AppTurismoCity/files/11888861/Scrum.xlsx)


Excel de las historias de usuario, dos por cada uno

**Comment by zoeggr** [comment]
Como developer Team. Quiero desarrollar la página, autoorganizarme y autogestionarme para conseguir entregar el objetivo desarrollado en su máximo esplendor

**Comment by zoeggr** [comment]
Como desarrolladora del Front en las ventanas de inicio y turismo en la página. Quiero generar una visualización correcta y estable para que el recorrido del cliente sea agradable y claro.

**Comment by Angie222** [comment]
Como product onwer. Quiero administrar y priorizar el trabajo pendiente del equipo y apoyarlo en la entrega de valor, contribuyendo a la visión y hoja de ruta para obtener y aplicar comentarios.

**Comment by Angie222** [comment]
Como creadora del proyecto en github y administradora de git que lo relaciona. Quiero almacenar la información y los cambios constantes para darles las tareas a cada participante del grupo y generar una estructura en la producción de la página web.

**Comment by estelaarguello7773** [comment]
Como recolectora de información. Quiero administrar datos claros y concisos para dar el correcto conocimiento de la ciudad, así los extranjeros puedan guiarse de forma correcta disfrutando de los espacios más conocidos hasta los más simples pero cómodos.

**Comment by estelaarguello7773** [comment]
Como recolectora de información. Quiero organizar y guardar el conocimiento ya obtenido para que en caso de alguna pérdida o confusión, el equipo pueda aclarar toda discusión entre ellos.

**Comment by AbelBovo83** [comment]
Como creador del diseño Quiero realizar un croquis de la página para comenzar el desarrollo del código en el Front-end

**Comment by AbelBovo83** [comment]
Como Scrum Master. Quiero entrenar y facilitar las dificultades de mis compañeras para encontrar soluciones y acelerar el ritmo de producción.

**Comment by Mili200410** [comment]
Como developer Team. Quiero crear diseñar e implementar con mi conocimiento la entrega de manera correcta para cumplir las expectativas dadas en la página de turismo.

**Comment by Mili200410** [comment]
Como desarrolladora del Front en las ventanas de contacto, mapa, shopping y video. Quiero generar un balance visual y la correcta cantidad de información para dar una buena imagen de la ciudad asi los habitantes que no forman parte decidan recorrernos.

**Comment by merceaudisio** [comment]
Como product manager. Quiero guiar la exploración continua y desenvolverme en la guía de la visión y la hoja de ruta para informar de el desarrollo al product owner.

**Comment by merceaudisio** [comment]
Como product manager. Quiero gestionar y priorizar la acumulación de tareas y definir y cuantificar el valor que debe tener el proyecto para que haya un orden de gestión y crear el producto a la altura del valor decidido.
